### ISSUE TITLE
WP errors

### ISSUE THREAD

**Issue by katana150** [Electra-project/Electra-Open-Paper#6]
I found 3 issues while reading the whitepaper.

1. Page 4:
Digital currency was created to bring change to the financial world through 
the decentralisation and disintermediation of the global financial ecosystem. 

(Issue fixed)

2.  Page 8
NIST5  is  an algorithm  developed  using  the  best  features  of  the  five  SHA-3  finalist algorithms 
as selected by the National Institute of Science and Technology of America.

(Issue Fixed)

3.  Page 15 Diagram step 5

(Issue Fixed )

katana150

**Comment by awpcrypto** [comment]
Hi! If you can, please open a pull request with the proposed changes. It will make it easier to incorporate into the main repository.

Cheers.

**Comment by katana150** [comment]
Issue taken care of.
